"""init commit

Revision ID: 838c11273515
Revises: 5cdb2af78f3c
Create Date: 2022-07-14 15:32:24.737883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '838c11273515'
down_revision = '5cdb2af78f3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_column('account', 'editor')
    op.drop_column('account', 'creator')
    op.drop_column('permission', 'editor')
    op.drop_column('permission', 'creator')
    op.drop_column('role', 'editor')
    op.drop_column('role', 'creator')
    op.drop_column('role_permission', 'editor')
    op.drop_column('role_permission', 'creator')
    op.drop_column('user', 'editor')
    op.drop_column('user', 'creator')
    op.drop_column('user_group', 'editor')
    op.drop_column('user_group', 'creator')
    op.drop_column('user_group_role', 'editor')
    op.drop_column('user_group_role', 'creator')
    op.drop_column('user_group_user', 'editor')
    op.drop_column('user_group_user', 'creator')
    op.drop_column('user_role', 'editor')
    op.drop_column('user_role', 'creator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('creator', mysql.VARCHAR(length=32), nullable=True, comment='创建人'))
    op.add_column('user_role', sa.Column('editor', mysql.VARCHAR(length=32), nullable=True, comment='修改人'))
    op.add_column('user_group_user', sa.Column('creator', mysql.VARCHAR(length=32), nullable=True, comment='创建人'))
    op.add_column('user_group_user', sa.Column('editor', mysql.VARCHAR(length=32), nullable=True, comment='修改人'))
    op.add_column('user_group_role', sa.Column('creator', mysql.VARCHAR(length=32), nullable=True, comment='创建人'))
    op.add_column('user_group_role', sa.Column('editor', mysql.VARCHAR(length=32), nullable=True, comment='修改人'))
    op.add_column('user_group', sa.Column('creator', mysql.VARCHAR(length=32), nullable=True, comment='创建人'))
    op.add_column('user_group', sa.Column('editor', mysql.VARCHAR(length=32), nullable=True, comment='修改人'))
    op.add_column('user', sa.Column('creator', mysql.VARCHAR(length=36), nullable=True, comment='创建人'))
    op.add_column('user', sa.Column('editor', mysql.VARCHAR(length=36), nullable=True, comment='修改人'))
    op.add_column('role_permission', sa.Column('creator', mysql.VARCHAR(length=32), nullable=True, comment='创建人'))
    op.add_column('role_permission', sa.Column('editor', mysql.VARCHAR(length=32), nullable=True, comment='修改人'))
    op.add_column('role', sa.Column('creator', mysql.VARCHAR(length=32), nullable=True, comment='创建人'))
    op.add_column('role', sa.Column('editor', mysql.VARCHAR(length=32), nullable=True, comment='修改人'))
    op.add_column('permission', sa.Column('creator', mysql.VARCHAR(length=32), nullable=True, comment='创建人'))
    op.add_column('permission', sa.Column('editor', mysql.VARCHAR(length=32), nullable=True, comment='修改人'))
    op.add_column('account', sa.Column('creator', mysql.VARCHAR(length=36), nullable=False, comment='创建人'))
    op.add_column('account', sa.Column('editor', mysql.VARCHAR(length=36), nullable=False, comment='修改人'))
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
